### ISSUE TITLE
插件需要额外安装依赖才能运行成功，首页文档未说明 `@lint-md/core` 依赖需要安装

### ISSUE THREAD

**Issue by ruan-cat** [lint-md/prettier-plugin#1]
插件需要额外安装依赖才能运行成功，首页文档未说明 `@lint-md/core` 依赖需要安装。

请及时更新文档，在 README.md 内说明清楚本依赖需要额外安装 @lint-md/core 。

**Comment by bosens-China** [comment]
@lint-md/core 作为dependencies依赖会自动安装，可以给出步骤复现的形式吗

**Comment by ruan-cat** [comment]
关闭。prettier-plugin-lint-md 升级到 1.0.1 后无误。在一个 monorepo 项目内，给root根包安装依赖，经测试无误。vscode的prettier插件可以正常调用此插件并工作。
